### PR TITLE
FIx issue #62 to support float as size_kb in create_temp_file() 

### LINKED ISSUE #62: create_temp_file() need to create in bytes or accept float as parameter
For dis upload scenario, the size should be 1024*x + 512 bytes, which will require size with "x.5" kb

### PR DESCRIPTION
**Pull request by Juliehzl**
fix #62

### CODE REVIEW

**Comment by qwordy** [comment]
Maybe you can add a description of `size_kb` to declare that it supports float number.
```
def create_temp_file(self, size_kb, full_random=False):
```

**Comment by Juliehzl** [comment]
> Maybe you can add a description of `size_kb` to declare that it supports float number.
> 
> ```
> def create_temp_file(self, size_kb, full_random=False):
> ```

sure

**Review by qwordy — CHANGES_REQUESTED** [review]
Maybe you can add a description of `size_kb` to declare that it supports float number.
```
def create_temp_file(self, size_kb, full_random=False):
```

**Review by qwordy — APPROVED** [review]

**Review by haroldrandom — APPROVED** [review]

**Pull request merged**
